---
- name: Estimate if installed
  stat:
    path: "{{ sops_bin_path }}"
  register: sops_bin

- name: Estimate installed version
  command: "{{ sops_bin_path }} --version"
  when: sops_bin.stat.exists
  register: sops_installed_version
  changed_when: false

- name: Try to parse installed version
  set_fact:
    installed_version: "{{
      sops_installed_version.stdout_lines[0]
      | regex_search(regexp,'\\1')
      | first
      }}"
  vars:
    regexp: ^sops ([0-9]+\.[0-9]+\.[0-9]+)( \(latest\))?$
  when: sops_installed_version.stdout is defined

- debug:
    msg: "Installed version: {{ installed_version }}"
  when: installed_version is defined

- debug:
    msg: "Installed version: <none>"
  when: installed_version is not defined
