---
- include: estimate_installed_version.yml

- include: estimate_latest_version.yml
  when: version is not defined
    or version | length < 1

- include: estimate_version_to_be_installed.yml

- name: Download bin file
  get_url:
    url:
      "https://github.com/mozilla/sops/releases/\
      download/{{ version_to_be_installed }}/\
      sops-{{ version_to_be_installed }}.linux"
    dest: "{{ sops_bin_path }}"
    mode: 0755
    force: true
  when: installed_version is not defined
    or version_to_be_installed != installed_version
